export const LANGUAGES = [
  { code: 'es', label: 'Español' },
  { code: 'en', label: 'English' },
  { code: 'de', label: 'Deutsch' },
  { code: 'zh', label: '中文' },
  { code: 'ru', label: 'Русский' },
  { code: 'fr', label: 'Français' },
  { code: 'pt', label: 'Português' }
];

export const translations = {
  es: {
    home: 'Inicio', howToGet: 'Cómo llegar', faq: 'FAQ guía', searchRoute: 'Buscar vía', routeName: 'Nombre de la vía...',
    noPhoto: 'Sin foto', grade: 'Grado', noGrade: 'Sin grado', noDescription: 'Todavía no hay una descripción cargada para esta vía.',
    noMatches: 'No encontramos vías con un nombre similar.', goHome: 'Ir al inicio', openMenu: 'Abrir menú', closeMenu: 'Cerrar menú', language: 'Idioma', accountMenu: 'Menú de usuario', gradeSystem: 'Sistema de graduación',
    loadErrorTitle: 'No se pudo cargar la información en este entorno', loadErrorHint: 'En tu entorno local ejecuta npm install y verifica acceso de red y disponibilidad de la API pública de theCrag.',
    subsectorsAria: 'Subsectores de Potrero Alto',
    howToGetTitle: 'Cómo llegar', howToGetText: 'Potrero Alto está ubicado en Q8370 San Martín de los Andes, Neuquén. Podés usar el siguiente mapa para ver el punto exacto del sector.', mapTitle: 'Mapa de Potrero Alto',
    ratingSystem: 'Sistema de puntuación', ratingText1: 'En los resultados de búsqueda, la valoración de cada vía aparece con una combinación de emojis en este orden:', ratingText2: 'A mayor cantidad de símbolos, mejor puntuada está la vía por la comunidad. Si no ves emojis, significa que todavía no tiene puntuación cargada.',
    faqTitle: 'FAQ: cómo entender la guía de escalada', faqDistribution: 'Distribución de subsectores en el predio', faqDistributionText: 'Esta imagen muestra la distribución de los subsectores dentro del Predio Potrero Alto para que puedas ubicarte más rápido al llegar.',
    faqSubsector: '¿Qué muestra cada subsector?', faqSubsectorText: 'Cada subsector agrupa las vías por pared o zona. Ahí vas a encontrar cantidad de rutas, dificultad, descripciones y, cuando está disponible, foto de referencia.',
    faqHistogram: '¿Cómo uso el histograma de grados?', faqHistogramText1: 'El gráfico de distribución te ayuda a ver rápidamente si el sector tiene más rutas fáciles, intermedias o duras.', faqHistogramText2: 'Escala de colores: verde (fácil), azul (intermedio), rojo (difícil), rojo oscuro (muy difícil).',
    chartByGrade: 'Distribución de vías por grado', withGrade: 'con grado', routesAtGrade: '{count} vías en grado {grade}',
    seeSubsectorRoutes: 'Ver rutas del subsector {name}', subsectorImage: 'Imagen del subsector {name}', routesCount: '{count} {routeWord}', routeWordOne: 'ruta', routeWordMany: 'rutas',
    photo: 'Foto', ratingOutOf5: 'Valoración {stars} de 5', close: 'Cerrar', gradesIn: 'Grados en {name}', noRoutes: 'Sin vías registradas en este subsector.', routeImage: 'Imagen de la vía {name}'
  },
  en: {
    home: 'Home', howToGet: 'How to get there', faq: 'Guide FAQ', searchRoute: 'Search route', routeName: 'Route name...', noPhoto: 'No photo',
    grade: 'Grade', noGrade: 'No grade', noDescription: 'No description is available for this route yet.', noMatches: 'No similar route names were found.',
    goHome: 'Go to home', openMenu: 'Open menu', closeMenu: 'Close menu', language: 'Language', accountMenu: 'User menu', gradeSystem: 'Grade system', loadErrorTitle: 'Could not load data in this environment',
    loadErrorHint: 'Run npm install locally and verify network access and availability of the public theCrag API.', subsectorsAria: 'Potrero Alto subsectors',
    howToGetTitle: 'How to get there', howToGetText: 'Potrero Alto is located at Q8370 San Martín de los Andes, Neuquén. Use the map below to see the exact location.', mapTitle: 'Potrero Alto map',
    ratingSystem: 'Rating system', ratingText1: 'In search results, each route rating appears as emojis in this order:', ratingText2: 'More symbols mean a better community rating. If there are no emojis, no rating has been added yet.',
    faqTitle: 'FAQ: how to read the climbing guide', faqDistribution: 'Subsector layout', faqDistributionText: 'This image shows the distribution of subsectors inside Potrero Alto.', faqSubsector: 'What does each subsector show?', faqSubsectorText: 'Each subsector groups routes by wall or area with quantity, grade, descriptions and photos when available.', faqHistogram: 'How do I use the grade histogram?', faqHistogramText1: 'The chart helps you quickly see if there are more easy, intermediate or hard routes.', faqHistogramText2: 'Color scale: green (easy), blue (intermediate), red (hard), dark red (very hard).',
    chartByGrade: 'Route distribution by grade', withGrade: 'with grade', routesAtGrade: '{count} routes at grade {grade}',
    seeSubsectorRoutes: 'See routes in subsector {name}', subsectorImage: 'Image of subsector {name}', routesCount: '{count} {routeWord}', routeWordOne: 'route', routeWordMany: 'routes', photo: 'Photo', ratingOutOf5: 'Rating {stars} of 5', close: 'Close', gradesIn: 'Grades in {name}', noRoutes: 'No routes registered in this subsector.', routeImage: 'Image of route {name}'
  },
  de: { home: 'Start', howToGet: 'Anfahrt', faq: 'FAQ', searchRoute: 'Route suchen', routeName: 'Routenname...', noPhoto: 'Kein Foto', grade: 'Grad', noGrade: 'Ohne Grad', noDescription: 'Für diese Route gibt es noch keine Beschreibung.', noMatches: 'Keine ähnlichen Routen gefunden.', goHome: 'Zur Startseite', openMenu: 'Menü öffnen', closeMenu: 'Menü schließen', language: 'Sprache', loadErrorTitle: 'Daten konnten in dieser Umgebung nicht geladen werden', loadErrorHint: 'Lokal npm install ausführen und Netzwerk/API-Zugriff prüfen.', subsectorsAria: 'Subsektoren von Potrero Alto', howToGetTitle: 'Anfahrt', howToGetText: 'Potrero Alto befindet sich in Q8370 San Martín de los Andes, Neuquén.', mapTitle: 'Karte von Potrero Alto', ratingSystem: 'Bewertungssystem', ratingText1: 'In den Suchergebnissen erscheint die Bewertung als Emojis in dieser Reihenfolge:', ratingText2: 'Mehr Symbole bedeuten bessere Bewertung.', faqTitle: 'FAQ: Kletterführer verstehen', faqDistribution: 'Verteilung der Subsektoren', faqDistributionText: 'Dieses Bild zeigt die Verteilung der Subsektoren.', faqSubsector: 'Was zeigt jeder Subsektor?', faqSubsectorText: 'Jeder Subsektor gruppiert Routen nach Wand oder Bereich.', faqHistogram: 'Wie nutze ich das Histogramm?', faqHistogramText1: 'Das Diagramm zeigt schnell die Schwierigkeit-Verteilung.', faqHistogramText2: 'Farben: grün, blau, rot, dunkelrot.', chartByGrade: 'Routenverteilung nach Grad', withGrade: 'mit Grad', routesAtGrade: '{count} Routen im Grad {grade}', seeSubsectorRoutes: 'Routen im Subsektor {name} ansehen', subsectorImage: 'Bild des Subsektors {name}', routesCount: '{count} {routeWord}', routeWordOne: 'Route', routeWordMany: 'Routen', photo: 'Foto', ratingOutOf5: 'Bewertung {stars} von 5', close: 'Schließen', gradesIn: 'Grade in {name}', noRoutes: 'Keine Routen in diesem Subsektor.', routeImage: 'Bild der Route {name}' },
  zh: { home: '主页', howToGet: '如何到达', faq: '常见问题', searchRoute: '搜索线路', routeName: '线路名称...', noPhoto: '无照片', grade: '难度', noGrade: '无难度', noDescription: '该线路暂无描述。', noMatches: '未找到相似线路。', goHome: '返回主页', openMenu: '打开菜单', closeMenu: '关闭菜单', language: '语言', loadErrorTitle: '当前环境无法加载数据', loadErrorHint: '请在本地运行 npm install，并检查网络和 theCrag API。', subsectorsAria: 'Potrero Alto 分区', howToGetTitle: '如何到达', howToGetText: 'Potrero Alto 位于 Q8370 San Martín de los Andes, Neuquén。', mapTitle: 'Potrero Alto 地图', ratingSystem: '评分系统', ratingText1: '搜索结果中，评分会按以下顺序显示表情：', ratingText2: '符号越多表示评分越高。', faqTitle: 'FAQ：如何阅读攀岩指南', faqDistribution: '分区分布', faqDistributionText: '这张图显示了分区分布。', faqSubsector: '每个分区显示什么？', faqSubsectorText: '每个分区按岩壁或区域汇总线路。', faqHistogram: '如何使用难度柱状图？', faqHistogramText1: '图表帮助你快速了解易中难线路分布。', faqHistogramText2: '颜色：绿、蓝、红、深红。', chartByGrade: '按难度分布', withGrade: '有难度', routesAtGrade: '{count} 条线路，难度 {grade}', seeSubsectorRoutes: '查看分区 {name} 线路', subsectorImage: '分区 {name} 图片', routesCount: '{count} {routeWord}', routeWordOne: '条线路', routeWordMany: '条线路', photo: '照片', ratingOutOf5: '评分 {stars}/5', close: '关闭', gradesIn: '{name} 难度', noRoutes: '该分区暂无线路。', routeImage: '线路 {name} 图片' },
  ru: { home: 'Главная', howToGet: 'Как добраться', faq: 'FAQ', searchRoute: 'Поиск маршрута', routeName: 'Название маршрута...', noPhoto: 'Нет фото', grade: 'Категория', noGrade: 'Без категории', noDescription: 'Описание для этого маршрута пока отсутствует.', noMatches: 'Похожие маршруты не найдены.', goHome: 'На главную', openMenu: 'Открыть меню', closeMenu: 'Закрыть меню', language: 'Язык', loadErrorTitle: 'Не удалось загрузить данные в этой среде', loadErrorHint: 'Запустите npm install локально и проверьте сеть/API theCrag.', subsectorsAria: 'Секторы Potrero Alto', howToGetTitle: 'Как добраться', howToGetText: 'Potrero Alto находится по адресу Q8370 San Martín de los Andes, Neuquén.', mapTitle: 'Карта Potrero Alto', ratingSystem: 'Система оценок', ratingText1: 'В результатах поиска рейтинг маршрута отображается эмодзи в порядке:', ratingText2: 'Чем больше символов, тем выше оценка.', faqTitle: 'FAQ: как читать гайд', faqDistribution: 'Распределение секторов', faqDistributionText: 'Изображение показывает расположение секторов.', faqSubsector: 'Что показывает каждый сектор?', faqSubsectorText: 'Каждый сектор группирует маршруты по стене или зоне.', faqHistogram: 'Как использовать гистограмму?', faqHistogramText1: 'График показывает распределение по сложности.', faqHistogramText2: 'Цвета: зелёный, синий, красный, тёмно-красный.', chartByGrade: 'Распределение по категориям', withGrade: 'с категорией', routesAtGrade: '{count} маршрутов категории {grade}', seeSubsectorRoutes: 'Показать маршруты сектора {name}', subsectorImage: 'Изображение сектора {name}', routesCount: '{count} {routeWord}', routeWordOne: 'маршрут', routeWordMany: 'маршрутов', photo: 'Фото', ratingOutOf5: 'Оценка {stars} из 5', close: 'Закрыть', gradesIn: 'Категории в {name}', noRoutes: 'В этом секторе нет маршрутов.', routeImage: 'Изображение маршрута {name}' },
  fr: { home: 'Accueil', howToGet: 'Comment y aller', faq: 'FAQ', searchRoute: 'Chercher une voie', routeName: 'Nom de la voie...', noPhoto: 'Sans photo', grade: 'Cotation', noGrade: 'Sans cotation', noDescription: 'Aucune description disponible pour cette voie.', noMatches: 'Aucune voie similaire trouvée.', goHome: 'Aller à l’accueil', openMenu: 'Ouvrir le menu', closeMenu: 'Fermer le menu', language: 'Langue', loadErrorTitle: 'Impossible de charger les données dans cet environnement', loadErrorHint: 'Exécutez npm install en local et vérifiez réseau/API theCrag.', subsectorsAria: 'Sous-secteurs de Potrero Alto', howToGetTitle: 'Comment y aller', howToGetText: 'Potrero Alto est situé à Q8370 San Martín de los Andes, Neuquén.', mapTitle: 'Carte de Potrero Alto', ratingSystem: 'Système de notation', ratingText1: 'Dans les résultats, la note apparaît en emojis dans cet ordre :', ratingText2: 'Plus de symboles = meilleure note.', faqTitle: 'FAQ : comprendre le topo', faqDistribution: 'Répartition des sous-secteurs', faqDistributionText: 'Cette image montre la répartition des sous-secteurs.', faqSubsector: 'Que montre chaque sous-secteur ?', faqSubsectorText: 'Chaque sous-secteur regroupe les voies par mur ou zone.', faqHistogram: 'Comment utiliser l’histogramme ?', faqHistogramText1: 'Le graphique montre rapidement la difficulté moyenne du secteur.', faqHistogramText2: 'Couleurs : vert, bleu, rouge, rouge foncé.', chartByGrade: 'Répartition des voies par cotation', withGrade: 'avec cotation', routesAtGrade: '{count} voies en cotation {grade}', seeSubsectorRoutes: 'Voir les voies du sous-secteur {name}', subsectorImage: 'Image du sous-secteur {name}', routesCount: '{count} {routeWord}', routeWordOne: 'voie', routeWordMany: 'voies', photo: 'Photo', ratingOutOf5: 'Note {stars} sur 5', close: 'Fermer', gradesIn: 'Cotations de {name}', noRoutes: 'Aucune voie enregistrée dans ce sous-secteur.', routeImage: 'Image de la voie {name}' },
  pt: { home: 'Início', howToGet: 'Como chegar', faq: 'FAQ', searchRoute: 'Buscar via', routeName: 'Nome da via...', noPhoto: 'Sem foto', grade: 'Grau', noGrade: 'Sem grau', noDescription: 'Ainda não há descrição para esta via.', noMatches: 'Não encontramos vias com nome parecido.', goHome: 'Ir para o início', openMenu: 'Abrir menu', closeMenu: 'Fechar menu', language: 'Idioma', accountMenu: 'Menú de usuario', gradeSystem: 'Sistema de graduación', loadErrorTitle: 'Não foi possível carregar os dados neste ambiente', loadErrorHint: 'No ambiente local rode npm install e verifique rede/API theCrag.', subsectorsAria: 'Subsetores de Potrero Alto', howToGetTitle: 'Como chegar', howToGetText: 'Potrero Alto está em Q8370 San Martín de los Andes, Neuquén.', mapTitle: 'Mapa de Potrero Alto', ratingSystem: 'Sistema de pontuação', ratingText1: 'Nos resultados, a avaliação aparece com emojis nesta ordem:', ratingText2: 'Quanto mais símbolos, melhor a avaliação da via.', faqTitle: 'FAQ: como entender o guia', faqDistribution: 'Distribuição dos subsetores', faqDistributionText: 'Esta imagem mostra a distribuição dos subsetores.', faqSubsector: 'O que mostra cada subsetor?', faqSubsectorText: 'Cada subsetor agrupa vias por parede ou zona.', faqHistogram: 'Como usar o histograma de graus?', faqHistogramText1: 'O gráfico ajuda a ver rapidamente as vias fáceis, médias e difíceis.', faqHistogramText2: 'Cores: verde, azul, vermelho e vermelho escuro.', chartByGrade: 'Distribuição de vias por grau', withGrade: 'com grau', routesAtGrade: '{count} vias no grau {grade}', seeSubsectorRoutes: 'Ver vias do subsetor {name}', subsectorImage: 'Imagem do subsetor {name}', routesCount: '{count} {routeWord}', routeWordOne: 'via', routeWordMany: 'vias', photo: 'Foto', ratingOutOf5: 'Avaliação {stars} de 5', close: 'Fechar', gradesIn: 'Graus em {name}', noRoutes: 'Sem vias registradas neste subsetor.', routeImage: 'Imagem da via {name}' }
};

export function createTranslator(language) {
  return (key, params = {}) => {
    const template = translations[language]?.[key] ?? translations.es[key] ?? key;

    return Object.entries(params).reduce(
      (message, [paramKey, paramValue]) => message.replaceAll(`{${paramKey}}`, String(paramValue)),
      template
    );
  };
}
