-- Seed generado automáticamente desde src/lib/fallback-subsectors.js
BEGIN;

DELETE FROM routes WHERE sector_id = '6574670919';
DELETE FROM subsectors WHERE sector_id = '6574670919';
DELETE FROM sectors WHERE id = '6574670919';

INSERT INTO sectors (id, name, location, description) VALUES ('6574670919', 'Potrero Alto', 'San Luis, Argentina', 'Datos de respaldo locales para subsectores y vías. Se usan cuando la API de theCrag no está disponible.');

INSERT INTO subsectors (id, sector_id, name, sector, description, image, sort_order) VALUES ('fallback-pared-este', '6574670919', 'Cheto / Pared Este', 'Potrero Alto', 'Sector de deportiva con 8 vías equipadas.', NULL, 0);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('pared-este-1', '6574670919', 'fallback-pared-este', 'Viento Este', '6a+', 2, 'Sport', 'comparte descuelgue con "oveja negra"', 'https://image.thecrag.com/900x1600/99/1f/991f771cecdd3c54bd69eb340666dafdd7336140', 19, 9, 'Pelu Ka', '9 May 2025', NULL, NULL, NULL, NULL, 0);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('pared-este-2', '6574670919', 'fallback-pared-este', 'Oveja Negra', '7a', 1, 'Sport', 'comparte descuelgue con "viento este"', 'https://image.thecrag.com/900x1600/1d/ea/1dea28823fdd91f74aff205dd45094a03b855f7b', 20, 11, 'Pelu Ka', '14 May 2025', NULL, NULL, NULL, NULL, 1);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('pared-este-3', '6574670919', 'fallback-pared-este', 'Forza Giacomo', '6a+', 2, 'Sport', 'comparte descuelgue con "Luchetti quien te conoce"', 'https://image.thecrag.com/900x1600/1d/ea/1dea28823fdd91f74aff205dd45094a03b855f7b', 20, 10, 'Fede Aragno', '9 May 2025', NULL, NULL, NULL, NULL, 2);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('pared-este-4', '6574670919', 'fallback-pared-este', 'Luchetti quien te conoce', '6a+', 2, 'Sport', 'comparte descuelgue con "Forza Giacomo"', 'https://image.thecrag.com/900x1600/1d/ea/1dea28823fdd91f74aff205dd45094a03b855f7b', 20, 10, 'Fede Aragno', '14 May 2025', NULL, NULL, NULL, NULL, 3);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('pared-este-5', '6574670919', 'fallback-pared-este', 'Eh Japanese!', '6b', 2, 'Sport', 'comparte primeras 3 chapas con "Presto Pronta" y luego hacia la izquierda', 'https://image.thecrag.com/526x1600/98/13/98137902bc6f397f159ce7f76d21f253ddf206bb', 22, 12, 'Fede Aragno', '22 May 2025', NULL, NULL, NULL, NULL, 4);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('pared-este-6', '6574670919', 'fallback-pared-este', 'Presto Pronta', '6b', 2, 'Sport', 'comparte primeras 3 chapas con "Eh Japanese!" y luego hacia la derecha', 'https://image.thecrag.com/981x960/e1/bf/e1bf1371e852f43653297d897899d254c973f779', 15, 9, 'Fede Aragno', '20 May 2025', NULL, NULL, NULL, NULL, 5);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('pared-este-7', '6574670919', 'fallback-pared-este', 'Proyectando Valencia', '5+', 2, 'Sport', 'comparte descuelgue con "Presto Pronta"', 'https://image.thecrag.com/900x1600/30/41/3041dc67cc6fc99e68402ccde2b7a6d65fee5a58', 15, 9, 'Pelu Ka', '22 May 2025', NULL, NULL, NULL, NULL, 6);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('pared-este-8', '6574670919', 'fallback-pared-este', 'Palitos Salados 650', '6a', 2, 'Sport', '', 'https://image.thecrag.com/745x1600/cd/d8/cdd8ed757d48f2e89fa84416df64aadd8a8481bd', 15, 7, 'Pelu Ka', '20 May 2025', NULL, NULL, NULL, NULL, 7);

INSERT INTO subsectors (id, sector_id, name, sector, description, image, sort_order) VALUES ('fallback-canadon', '6574670919', 'Cañadón', 'Potrero Alto', 'Área deportiva corta con dos líneas.', NULL, 1);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('canadon-1', '6574670919', 'fallback-canadon', '3 hermanos', '6b', NULL, 'Sport', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('canadon-2', '6574670919', 'fallback-canadon', 'Monopoly', '6b', NULL, 'Sport', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);

INSERT INTO subsectors (id, sector_id, name, sector, description, image, sort_order) VALUES ('fallback-tablero', '6574670919', 'El Tablero', 'Potrero Alto', 'Sector principal con vías de deportiva variadas.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Chess_board_with_chess_set_in_opening_position_2012_PD_03.jpg/250px-Chess_board_with_chess_set_in_opening_position_2012_PD_03.jpg', 2);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('tablero-1', '6574670919', 'fallback-tablero', 'Duro al Pedal!', '5b', 2, 'Sport', '', 'https://image.thecrag.com/900x1600/e0/75/e075c88b4812dd53da3c0b722d2941753af4cddf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('tablero-2', '6574670919', 'fallback-tablero', 'La Chaquetuda', '5c+', 2, 'Sport', '', 'https://image.thecrag.com/900x1600/e0/75/e075c88b4812dd53da3c0b722d2941753af4cddf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('tablero-3', '6574670919', 'fallback-tablero', 'Vino & Keterolac', '6c/+', NULL, 'Sport', '', 'https://image.thecrag.com/900x1600/08/3e/083e09dcb3a3aa64df555d84c12104ecef1e01de', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('tablero-4', '6574670919', 'fallback-tablero', 'Biciequipadores', '7b/+', NULL, 'Sport', '', 'https://image.thecrag.com/900x1600/08/3e/083e09dcb3a3aa64df555d84c12104ecef1e01de', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('tablero-5', '6574670919', 'fallback-tablero', 'KuKuruch', '6b', 3, 'Sport', '', 'https://image.thecrag.com/960x1610/ad/26/ad26db1358a13ee970fac42f8cbf8aa05ee454a0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('tablero-6', '6574670919', 'fallback-tablero', 'Banquito para dos', '5b', 2, 'Sport', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('tablero-7', '6574670919', 'fallback-tablero', 'el banquito', '6a', NULL, 'Sport', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('tablero-8', '6574670919', 'fallback-tablero', 'El sheriff', '6a', 4, 'Sport', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 7);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('tablero-9', '6574670919', 'fallback-tablero', 'Jägermeister', '6a', NULL, 'Sport', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('tablero-10', '6574670919', 'fallback-tablero', 'CapricorniaBosh', '6b/b+', 2, 'Sport', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('tablero-11', '6574670919', 'fallback-tablero', 'Las damas primero', '6b', 5, 'Sport', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('tablero-12', '6574670919', 'fallback-tablero', 'El Peon', '6c', 2, 'Sport', '', 'https://image.thecrag.com/899x1599/e3/af/e3af4b6502756b857698771db3d5154521edd309', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('tablero-13', '6574670919', 'fallback-tablero', 'Enroque', '7a+', 1, 'Sport', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 12);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('tablero-14', '6574670919', 'fallback-tablero', 'Alfil', '7b+/c', NULL, 'Sport', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 13);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('tablero-15', '6574670919', 'fallback-tablero', 'Caballo', '7b', 3, 'Sport', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 14);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('tablero-16', '6574670919', 'fallback-tablero', 'Reina', '7a', 5, 'Sport', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('tablero-17', '6574670919', 'fallback-tablero', 'Enroque Largo', '7b/b+', 3, 'Sport', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('tablero-18', '6574670919', 'fallback-tablero', 'Jaque Permanente', '7a', 3, 'Sport', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17);

INSERT INTO subsectors (id, sector_id, name, sector, description, image, sort_order) VALUES ('fallback-derrumbe', '6574670919', 'El Derrumbe', 'Potrero Alto', 'Sector deportivo con desplome y vías largas.', NULL, 3);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('derrumbe-1', '6574670919', 'fallback-derrumbe', 'Matematicamenteposible', '7b+/c', 2, 'Sport', 'SICADA.', NULL, 25, 13, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('derrumbe-2', '6574670919', 'fallback-derrumbe', 'Generación Z', '6c/c+', 4, 'Sport', '', NULL, 22, 12, 'иван & juan Ramon', '12 Sep 2026', NULL, NULL, NULL, NULL, 1);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('derrumbe-3', '6574670919', 'fallback-derrumbe', 'Diamante', '7a', 4, 'Sport', 'En bruto', 'https://image.thecrag.com/1280x960/filters:rotate(270)/dc/b2/dcb2b678e32cdbf2601b1d71392acd513206152b', 20, 10, 'иван & JP', '15 May 2024', NULL, NULL, NULL, NULL, 2);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('derrumbe-4', '6574670919', 'fallback-derrumbe', 'Trébol', '6b+/c', 1, 'Sport', 'Es un terremoto(?)', NULL, 50, 24, 'иван & ATMAN', '12 Apr 2023', NULL, NULL, NULL, NULL, 3);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('derrumbe-5', '6574670919', 'fallback-derrumbe', 'Corazón', '7a+', 2, 'Sport', '¡PIM! ¡PAM! ¡PUM! ¡PLAS! ¡BOOM! ¡CRASH! ¡BANG! ¡ZAS! ¡BROOM! ¡CLANK! ¡TAC! ¡FLASH! 🚀', 'https://image.thecrag.com/1280x960/filters:rotate(270)/ee/ff/eeff0a21f93bc5522a6e2d1d84046068790662d6', 20, 11, 'иван', '25 Feb 2025', NULL, NULL, NULL, NULL, 4);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('derrumbe-6', '6574670919', 'fallback-derrumbe', 'Grandes Amigos', '7c', 3, 'Sport', '', NULL, 18, NULL, 'Tomy genova', '1 Apr 2025', 'Juan de la Canal', '10 May 2025', NULL, NULL, 5);

INSERT INTO subsectors (id, sector_id, name, sector, description, image, sort_order) VALUES ('fallback-chancheria', '6574670919', 'La Chanchería', 'Potrero Alto', 'Sector con rutas duras y proyectos.', NULL, 4);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('chancheria-1', '6574670919', 'fallback-chancheria', 'Motivación Peruana', 'Proyecto', 5, 'Sport', 'Aparque su llama del lado derecho del pie de vía, se recomienda el uso de maca peruana y casco.', NULL, 30, 22, 'иван & Eche', '5 Sep 2026', NULL, NULL, NULL, NULL, 0);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('chancheria-2', '6574670919', 'fallback-chancheria', 'Amigas y Rivales', '7c', NULL, 'Sport', '', NULL, 17, 7, 'simon de la Canal & Juan de la Canal', '14 Jan 2023', NULL, NULL, NULL, NULL, 1);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('chancheria-3', '6574670919', 'fallback-chancheria', 'Trago amargo', '7b+', NULL, 'Sport', '', NULL, 15, 7, 'Hernán Signorini', '15 Jan 2023', 'simon de la Canal', '27 Jan 2023', NULL, NULL, 2);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('chancheria-4', '6574670919', 'fallback-chancheria', 'Ricky in the flow', '7b', 1, 'Sport', '', NULL, 15, 7, 'Juan Pedalino & Lula Tiemroth', '27 Jan 2023', 'simon de la Canal', '31 Jan 2023', -40.13690463357635, -71.2524842958867, 3);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('chancheria-5', '6574670919', 'fallback-chancheria', 'Carancho come zorzal', '7b+', NULL, 'Sport', '', NULL, 15, 7, 'Lula Tiemroth & Juan Pedalino', '1 May 2021', 'Juan de la Canal', '14 Jan 2023', NULL, NULL, 4);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('chancheria-6', '6574670919', 'fallback-chancheria', 'El despilfarro', '7b+', NULL, 'Sport', '', NULL, 16, 11, 'Juan Pedalino & Lula Tiemroth', '1 Feb 2022', 'simon de la Canal', '7 Jan 2023', NULL, NULL, 5);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('chancheria-7', '6574670919', 'fallback-chancheria', 'Alien contento', '7b/b+', NULL, 'Sport', '', NULL, 17, NULL, 'Juan Pedalino & Lula Tiemroth', '1 May 2022', 'simon de la Canal', '10 Jan 2023', NULL, NULL, 6);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('chancheria-8', '6574670919', 'fallback-chancheria', 'Mamba Negra', '7b+', 4, 'Sport', '', NULL, 18, 14, 'Juan Pedalino & Lula Tiemroth', NULL, 'Juan de la Canal', '7 Jan 2025', NULL, NULL, 7);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('chancheria-9', '6574670919', 'fallback-chancheria', 'Libre de pecado', '6c', 5, 'Sport', 'El que este libre de pecado que vaya a pecar. Todavía hay tiempo. Se recomienda uso de casco, piedra devil', 'https://image.thecrag.com/1280x960/filters:rotate(270)/96/86/9686440c1a6bbdfb0ec31699fd39aeaa4fc89b54', 16, 10, 'juan Ramon & иван', NULL, 'nadina & Nadina Villa', '1 Nov 2024', NULL, NULL, 8);

INSERT INTO subsectors (id, sector_id, name, sector, description, image, sort_order) VALUES ('fallback-arco', '6574670919', 'El Arco', 'Potrero Alto', 'Área de deportiva junto a La Chanchería.', 'https://image.thecrag.com/1280x960/filters:rotate(270)/c3/6f/c36f6dad63f4a93876e600031a459dca0a8229b1', 5);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('arco-1', '6574670919', 'fallback-arco', 'Variante FisuraPreHistorica', '6b', NULL, 'Sport', 'Variante de "PreHistorica", empieza por la fisura y termina en la reunion de "PreHistorica"', NULL, 18, 10, 'JP', '1 Mayo 2025', NULL, NULL, NULL, NULL, 0);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('arco-2', '6574670919', 'fallback-arco', 'PreHistorica', '6a', NULL, 'Sport', 'Primer ruta del sector. Ubicada en el margen derecho de la chancheria equipada por el 2000', NULL, 18, 10, NULL, NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('arco-3', '6574670919', 'fallback-arco', 'ESTACIONAMIENTO MEDIDO', '6c+/7a', 3, 'Sport', 'Roca frágil, es recomendable el uso de casco.', 'https://image.thecrag.com/1280x960/8d/87/8d8736b9168cd854c0339fb5d7f46e2214433c6c', 20, 15, 'ivan & JB', '8 Oct 2024', 'JB', '17 Oct 2024', NULL, NULL, 2);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('arco-4', '6574670919', 'fallback-arco', 'Variante - Prohibido estacionar', '6b', 2, 'Sport', 'Variante de "Estacionamiento medido", termina en la reunion de "Musgotopia"', NULL, 16, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('arco-5', '6574670919', 'fallback-arco', 'Musgotopia', '6b', NULL, 'Sport', '', 'https://image.thecrag.com/1280x960/filters:rotate(270)/c3/6f/c36f6dad63f4a93876e600031a459dca0a8229b1', 18, 12, 'juan Ramon', '2 Abr 2025', NULL, NULL, NULL, NULL, 4);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('arco-6', '6574670919', 'fallback-arco', 'Sombra chinesca', '6b', 2, 'Sport', '', 'https://image.thecrag.com/1280x960/filters:rotate(270)/c3/6f/c36f6dad63f4a93876e600031a459dca0a8229b1', 11, 10, 'иван', '2 Abr 2025', NULL, NULL, NULL, NULL, 5);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('arco-7', '6574670919', 'fallback-arco', 'eЯЯeЯЯaЯa', '6a', 3, 'Sport', '', 'https://image.thecrag.com/960x2080/fa/49/fa49e54a00d2ac541f325e4c39b5f06c076187d7', 14, 7, NULL, NULL, 'Tomas Genova', '1 Abr 2025', NULL, NULL, 6);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('arco-8', '6574670919', 'fallback-arco', 'EmPotreBro', '6b', 4, 'Sport', 'Placa frontal', 'https://image.thecrag.com/1280x960/filters:rotate(270)/c3/6f/c36f6dad63f4a93876e600031a459dca0a8229b1', 14, 7, 'juan Ramon, иван & Tommy', '31 Mar 2025', 'иван', '31 Mar 2025', NULL, NULL, 7);

INSERT INTO subsectors (id, sector_id, name, sector, description, image, sort_order) VALUES ('fallback-croto', '6574670919', 'Croto', 'Potrero Alto', 'Subsector en desarrollo con líneas nuevas.', NULL, 6);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('croto-1', '6574670919', 'fallback-croto', 'sin terminar', 'Sin grado', NULL, 'Sport', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('croto-2', '6574670919', 'fallback-croto', 'Aliento de chancho', '8?', NULL, 'Sport', '', NULL, 22, 12, NULL, NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('croto-3', '6574670919', 'fallback-croto', 'Patada de chancho', '6c', 5, 'Sport', '', NULL, 14, 11, 'иван', '8 Feb 2026', 'Eche & e', '8 Feb 2026', NULL, NULL, 2);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('croto-4', '6574670919', 'fallback-croto', 'Mariscal the campo', 'Sin grado', NULL, 'Sport', '', NULL, 25, 13, NULL, NULL, NULL, NULL, NULL, NULL, 3);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('croto-5', '6574670919', 'fallback-croto', 'Se vienen cositas', '6b', 5, 'Sport', '', NULL, 18, 11, 'Cata Pinel', '8 Feb 2026', NULL, NULL, NULL, NULL, 4);
INSERT INTO routes (id, sector_id, subsector_id, name, grade, stars, type, description, image, length_meters, quickdraws, equipped_by, equipped_date, first_ascent_by, first_ascent_date, latitude, longitude, sort_order) VALUES ('croto-6', '6574670919', 'fallback-croto', 'Municipales', '6a+', 3, 'Sport', '', NULL, 13, 9, 'juan Ramon', '9 Feb 2026', 'juan Ramon', '9 Feb 2026', NULL, NULL, 5);

COMMIT;
